"""Executive insight generator (Phase 5.9).

Composes several INDEPENDENTLY-COMPUTED, verifiable observations into a board-ready
narrative — a headline plus grounded findings (overview, totals, distribution/range, top
driver, period-over-period trend, data quality). It builds on the Phase-2.6 principle: every
figure is calculated from the data here, never free-generated by a model, so nothing can be
fabricated. Each insight carries its raw `figures` so any number in the prose can be checked.

Stays honest under uncertainty: on tiny or unsuitable data it emits caveats and simply omits
the findings it can't support (a missing trend is never invented).
"""
from __future__ import annotations

import warnings

import pandas as pd


def _looks_numeric(series: pd.Series) -> bool:
    nonblank = series[series.notna() & (series.astype(str).str.strip() != "")]
    if len(nonblank) == 0:
        return False
    return bool(pd.to_numeric(nonblank, errors="coerce").notna().all())


def _is_serial(df: pd.DataFrame, col) -> bool:
    """True for a numeric column that identifies rows rather than measuring anything.

    Without this the summary narrated whatever numeric column came first, which on a real
    file produced "Total S.NO. is 216.7K" and "largest contributor at 0% of S.NO." —
    arithmetic that is perfectly correct and completely meaningless. A serial number is
    not a quantity, so totalling or averaging it says nothing.

    Two signals, either is enough: the column is NAMED like an identifier (reusing
    kg._id_like so this codebase keeps one definition), or it is a near-unique run of
    whole numbers, which is what a serial column looks like whatever it is called.
    """
    try:
        from .kg import _id_like
        if _id_like(col):
            return True
        series = pd.to_numeric(df[col], errors="coerce").dropna()
        if len(series) > 10 and series.nunique() / len(series) > 0.98:
            return bool((series % 1 == 0).all())
    except Exception:
        return False
    return False


# Measures whose values must not be added up. A percentage, a score, a rate or a GPA is
# a LEVEL, not a quantity: summing 548 CGPAs gives a real number that means nothing, which
# is the same failure as totalling a serial column. Averaging them is fine, so the range
# insight still applies — only "total" and "share of total" are withheld.
_NON_ADDITIVE_HINTS = (
    "%", "percent", "pct", "rate", "ratio", "score", "cgpa", "gpa", "grade",
    "avg", "average", "mean", "median", "index", "rating", "age",
)


def _is_additive(col) -> bool:
    name = str(col).strip().lower()
    return not any(h in name for h in _NON_ADDITIVE_HINTS)


def _abbrev(x: float) -> str:
    """Compact human number: 4,820,000 -> 4.82M, 18204 -> 18.2K (matches the app's style)."""
    ax = abs(x)
    if ax >= 1_000_000:
        return f"{x / 1_000_000:.2f}M"
    if ax >= 1_000:
        return f"{x / 1_000:.1f}K"
    return f"{int(x)}" if x == int(x) else f"{x:.2f}"


def _blank_mask(df: pd.DataFrame) -> pd.DataFrame:
    return df.isna() | (df.astype(str).apply(lambda s: s.str.strip() == ""))


def _date_column(df: pd.DataFrame):
    """A clear date column (name, parsed series) or (None, None). Numeric columns are never
    treated as dates, and ≥80% of non-blank values must parse."""
    for c in df.columns:
        s = df[c]
        if pd.api.types.is_datetime64_any_dtype(s):
            return c, s
        if _looks_numeric(s):
            continue
        nonblank = s[s.notna() & (s.astype(str).str.strip() != "")]
        if len(nonblank) < 3:
            continue
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            parsed = pd.to_datetime(nonblank, errors="coerce")
            if float(parsed.notna().mean()) >= 0.8:
                return c, pd.to_datetime(s, errors="coerce")
    return None, None


def _trend(df: pd.DataFrame, metric: str, mseries: pd.Series) -> dict | None:
    """Period-over-period on the last two months of a clean date column. None when there's no
    date column, fewer than two periods, or a zero base — never a guess."""
    dcol, dt = _date_column(df)
    if dcol is None:
        return None
    per = dt.dt.to_period("M")
    g = pd.DataFrame({"_p": per, "_v": mseries}).dropna(subset=["_p", "_v"]).groupby("_p")["_v"].sum().sort_index()
    if len(g) < 2:
        return None
    last, prev = float(g.iloc[-1]), float(g.iloc[-2])
    if prev == 0:
        return None
    pct = round((last - prev) / abs(prev) * 100)
    direction = "up" if last >= prev else "down"
    return {
        "kind": "trend",
        "text": (f"{metric} is {direction} {abs(pct)}% in {g.index[-1].strftime('%b %Y')} vs "
                 f"{g.index[-2].strftime('%b %Y')} ({_abbrev(last)} vs {_abbrev(prev)})."),
        "figures": {"metric": metric, "pct": pct, "last": round(last, 4), "prev": round(prev, 4),
                    "period": str(g.index[-1]), "prior_period": str(g.index[-2])},
    }


def generate(df: pd.DataFrame, title: str | None = None) -> dict:
    """A structured, grounded executive summary of `df`."""
    insights: list[dict] = []
    caveats: list[str] = []

    if df is None or len(df) == 0:
        return {"title": title, "headline": "No data to summarize.", "insights": [],
                "grounded": True, "caveats": ["The dataset is empty."]}

    n = len(df)
    cols = [str(c) for c in df.columns]
    numeric = [c for c in df.columns if _looks_numeric(df[c]) and not _is_serial(df, c)]

    insights.append({"kind": "overview", "text": f"{n:,} rows across {len(cols)} columns.",
                     "figures": {"rows": n, "columns": len(cols)}})
    if n < 3:
        caveats.append("Very little data — treat these as indicative, not conclusive.")

    if numeric:
        metric = str(numeric[0])
        v = pd.to_numeric(df[numeric[0]], errors="coerce")
        total, avg, mn, mx = float(v.sum()), float(v.mean()), float(v.min()), float(v.max())
        additive = _is_additive(metric)
        if additive:
            insights.append({"kind": "total", "text": f"Total {metric} is {_abbrev(total)}.",
                             "figures": {"metric": metric, "total": round(total, 4)}})
        insights.append({"kind": "range",
                         "text": f"{metric} averages {_abbrev(avg)}, ranging {_abbrev(mn)} to {_abbrev(mx)}.",
                         "figures": {"metric": metric, "avg": round(avg, 4), "min": mn, "max": mx}})

        # Top driver — only as a part-of-whole when contributions are non-negative and the
        # top is a sane 0–100% slice (mixed-sign data would give a fabricated-looking share).
        # The category must also GROUP the data: a column with one distinct value per row
        # (a Name) made a single person "the largest contributor", which is not a finding.
        cats = [c for c in df.columns
                if c not in numeric and 2 <= int(df[c].nunique(dropna=True)) <= min(40, n - 1)]
        if additive and cats and total > 0:
            cat = str(cats[0])
            g = (pd.DataFrame({"_c": df[cats[0]].astype(str), "_v": v})
                 .dropna(subset=["_v"]).groupby("_c")["_v"].sum())
            if len(g) >= 2 and float(g.min()) >= 0:
                top, tv = str(g.idxmax()), float(g.max())
                share = round(tv / total * 100)
                if 0 <= share <= 100:
                    insights.append({"kind": "top_driver",
                                     "text": f"{cat} “{top}” is the largest contributor at {share}% of {metric} ({_abbrev(tv)}).",
                                     "figures": {"category": cat, "top": top, "share_pct": share, "value": round(tv, 4)}})

        tr = _trend(df, metric, v)
        if tr:
            insights.append(tr)
    else:
        caveats.append("No numeric columns — the summary is limited to structure.")

    # Data quality: worst blank rate, if it's material.
    bm = _blank_mask(df)
    rates = (bm.sum() / n).sort_values(ascending=False)
    if len(rates) and float(rates.iloc[0]) >= 0.1:
        col, rate = str(rates.index[0]), float(rates.iloc[0])
        insights.append({"kind": "data_quality",
                         "text": f"Data quality note: '{col}' is {round(rate * 100)}% blank.",
                         "figures": {"column": col, "blank_rate": round(rate, 3)}})

    headline = _headline(insights)
    return {"title": title, "headline": headline, "insights": insights,
            "grounded": True, "caveats": caveats}


def _headline(insights: list[dict]) -> str:
    """The single most decision-relevant finding: a trend if there is one, else the top
    driver, else the total, else the overview."""
    by_kind = {i["kind"]: i for i in insights}
    for kind in ("trend", "top_driver", "total", "overview"):
        if kind in by_kind:
            return by_kind[kind]["text"]
    return insights[0]["text"] if insights else "No findings."


def as_text(summary: dict) -> str:
    """A plain-text, copy-into-a-deck rendering of the narrative."""
    lines = [summary["headline"]]
    for i in summary["insights"]:
        if i["kind"] != "overview" and i["text"] != summary["headline"]:
            lines.append(f"• {i['text']}")
    for cav in summary.get("caveats", []):
        lines.append(f"(Note: {cav})")
    return "\n".join(lines)
