"""Export a dataset to a shareable document (Phase 3.7).

Two formats beyond the existing .xlsx:
  • PDF  — a paginated table, drawn with PyMuPDF (already a dependency).
  • PPTX — one slide per table, built with python-pptx.

These are deliberately simple, faithful renderings of the data (headers + rows), capped
so a huge sheet can't produce a thousand-page PDF. The caller passes a {name: DataFrame}
mapping; both functions return bytes.
"""
from __future__ import annotations

import io

import fitz  # PyMuPDF
import pandas as pd

# Caps so an enormous sheet can't blow up the export.
_PDF_MAX_ROWS = 500
_PPTX_MAX_ROWS = 12
_PPTX_MAX_COLS = 8


def _cell(v) -> str:
    if v is None:
        return ""
    try:
        if isinstance(v, float) and pd.isna(v):
            return ""
    except Exception:
        pass
    return str(v)


# --------------------------------------------------------------------------- PDF
def tables_to_pdf(tables: dict[str, pd.DataFrame], title: str = "Sumio export") -> bytes:
    """Render tables as a landscape PDF: a heading per table, then a header row and the
    data rows, paginating when the page fills up."""
    doc = fitz.open()
    W, H = 842, 595  # A4 landscape (points)
    margin = 40
    line_h = 16
    fs = 9

    def new_page():
        return doc.new_page(width=W, height=H)

    for tname, df in tables.items():
        page = new_page()
        y = margin
        page.insert_text((margin, y + 6), title, fontsize=14, fontname="hebo")
        y += line_h + 8
        page.insert_text((margin, y), f"{tname}  ({len(df):,} rows)", fontsize=11, fontname="hebo")
        y += line_h + 4

        cols = [str(c) for c in df.columns] or ["(no columns)"]
        ncol = len(cols)
        col_w = (W - 2 * margin) / ncol
        max_chars = max(4, int(col_w / (fs * 0.5)))

        def draw_row(values, yy, bold=False):
            font = "hebo" if bold else "helv"
            for i, val in enumerate(values[:ncol]):
                text = _cell(val)
                if len(text) > max_chars:
                    text = text[: max_chars - 1] + "…"
                page.insert_text((margin + i * col_w + 2, yy), text, fontsize=fs, fontname=font)

        # Header
        draw_row(cols, y, bold=True)
        page.draw_line((margin, y + 3), (W - margin, y + 3), width=0.6)
        y += line_h

        shown = min(len(df), _PDF_MAX_ROWS)
        for r in range(shown):
            if y > H - margin:
                page = new_page()
                y = margin
                draw_row(cols, y, bold=True)
                page.draw_line((margin, y + 3), (W - margin, y + 3), width=0.6)
                y += line_h
            draw_row(list(df.iloc[r]), y)
            y += line_h

        if len(df) > shown:
            page.insert_text(
                (margin, min(y + 4, H - margin // 2)),
                f"… {len(df) - shown:,} more rows not shown in this PDF export.",
                fontsize=8, fontname="helv", color=(0.4, 0.4, 0.4),
            )

    if doc.page_count == 0:
        doc.new_page(width=W, height=H).insert_text((margin, margin), title, fontsize=14, fontname="hebo")
    out = doc.tobytes()
    doc.close()
    return out


# -------------------------------------------------------------------------- PPTX
def tables_to_pptx(tables: dict[str, pd.DataFrame], title: str = "Sumio export") -> bytes:
    """Build a deck: a title slide, then one slide per table with a (capped) table shape."""
    from pptx import Presentation
    from pptx.util import Inches, Pt

    prs = Presentation()

    title_slide = prs.slides.add_slide(prs.slide_layouts[0])
    title_slide.shapes.title.text = title
    if len(title_slide.placeholders) > 1:
        title_slide.placeholders[1].text = "Generated by Sumio"

    for tname, df in tables.items():
        slide = prs.slides.add_slide(prs.slide_layouts[5])  # Title Only
        slide.shapes.title.text = f"{tname} ({len(df):,} rows)"

        cols = [str(c) for c in df.columns][:_PPTX_MAX_COLS] or ["(no columns)"]
        nrows = min(len(df), _PPTX_MAX_ROWS)
        ncol = len(cols)

        shape = slide.shapes.add_table(
            nrows + 1, ncol, Inches(0.5), Inches(1.6), Inches(9.0), Inches(0.4 * (nrows + 1))
        )
        table = shape.table
        for c, name in enumerate(cols):
            cell = table.cell(0, c)
            cell.text = name
            cell.text_frame.paragraphs[0].font.size = Pt(12)
            cell.text_frame.paragraphs[0].font.bold = True
        for r in range(nrows):
            row = df.iloc[r]
            for c, name in enumerate(df.columns[:ncol]):
                cell = table.cell(r + 1, c)
                cell.text = _cell(row[name])
                cell.text_frame.paragraphs[0].font.size = Pt(10)

        if len(df) > nrows or len(df.columns) > ncol:
            note = slide.shapes.add_textbox(Inches(0.5), Inches(6.6), Inches(9.0), Inches(0.4))
            note.text_frame.text = (
                f"Showing {nrows} of {len(df):,} rows"
                + (f" and {ncol} of {len(df.columns)} columns" if len(df.columns) > ncol else "")
                + " — full data is in the spreadsheet export."
            )
            note.text_frame.paragraphs[0].font.size = Pt(9)

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()


def render(tables: dict[str, pd.DataFrame], fmt: str, title: str = "Sumio export") -> tuple[bytes, str]:
    """Render tables to `fmt` ('pdf' | 'pptx'). Returns (bytes, file_extension)."""
    fmt = (fmt or "").lower()
    if fmt == "pdf":
        return tables_to_pdf(tables, title), "pdf"
    if fmt in ("pptx", "ppt", "powerpoint"):
        return tables_to_pptx(tables, title), "pptx"
    raise ValueError(f"Unsupported export format: {fmt!r} (use 'pdf' or 'pptx').")
